spring:
  datasource:

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mshrworker
    username: postgres
    password: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true