spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mshrworker
    username: hrworker
    password: hrworker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
