version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hrworker
      POSTGRES_PASSWORD: hrworker
      POSTGRES_DB: mshrworker